In [3]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in C:\Users\Huda.Rauf\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Huda.Rauf\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Huda.Rauf\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Huda.Rauf\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in C:\Users\Huda.Rauf\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

In [131]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\Huda.Rauf\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Huda.Rauf\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\Huda.Rauf\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\Huda.Rauf\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\Huda.Rauf\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\Huda.Rauf\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
#Reading the dataset
df = pd.read_excel("../data/Online Retail.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: '../data/Online Retail.xlsx'

**Exploratory Data Analysis**

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [8]:
df.shape

(541909, 8)

In [9]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [10]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [11]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [12]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  541909.000000                      541909  541909.000000  406829.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114   15287.690570
min    -80995.000000         2010-12-01 08:26:00  -11062.060000   12346.000000
25%         1.000000         2011-03-28 11:34:00       1.250000   13953.000000
50%         3.000000         2011-07-19 17:17:00       2.080000   15152.000000
75%        10.000000         2011-10-19 11:27:00       4.130000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       218.081158                         NaN      96.759853    1713.600303

In [13]:
df.isnull()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
541904,False,False,False,False,False,False,False,False
541905,False,False,False,False,False,False,False,False
541906,False,False,False,False,False,False,False,False
541907,False,False,False,False,False,False,False,False
541908,False,False,False,False,False,False,False,False

In [14]:
df[df["CustomerID"].isnull()]["Quantity"].describe()

count    135080.000000
mean          1.995573
std          66.696153
min       -9600.000000
25%           1.000000
50%           1.000000
75%           3.000000
max        5568.000000
Name: Quantity, dtype: float64

In [15]:
df[df["Quantity"] < 0].head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,2010-12-01 14:33:00,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,2010-12-01 14:33:00,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2010-12-01 14:33:00,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,2010-12-01 14:33:00,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,2010-12-01 14:33:00,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,2010-12-01 14:33:00,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,2010-12-01 14:33:00,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,2010-12-01 14:33:00,0.85,12472.0,Germany

In [16]:
df["InvoiceNo"].astype(str).str.startswith("C").sum()

np.int64(9288)

In [17]:
(df["InvoiceNo"].astype(str).str.startswith("C").mean()) * 100

np.float64(1.7139409015166756)

In [18]:
df[df["Quantity"] == -80995]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446.0,United Kingdom

In [19]:
df["InvoiceNo"].astype(str).str[0].value_counts()

InvoiceNo
5    532618
C      9288
A         3
Name: count, dtype: int64

In [20]:
df[~df["InvoiceNo"].astype(str).str.isnumeric()]["InvoiceNo"].unique()[:50]

array(['C536379', 'C536383', 'C536391', 'C536506', 'C536543', 'C536548',
       'C536606', 'C536622', 'C536625', 'C536642', 'C536734', 'C536737',
       'C536757', 'C536758', 'C536760', 'C536807', 'C536812', 'C536814',
       'C536815', 'C536816', 'C536817', 'C536818', 'C536820', 'C536822',
       'C536825', 'C536826', 'C536827', 'C536828', 'C536829', 'C536850',
       'C536853', 'C536854', 'C536855', 'C536978', 'C536979', 'C537024',
       'C537039', 'C537043', 'C537132', 'C537143', 'C537157', 'C537164',
       'C537203', 'C537232', 'C537234', 'C537251', 'C537314', 'C537320',
       'C537333', 'C537373'], dtype=object)

In [21]:
df[df["InvoiceNo"].astype(str).str.startswith("C")]["Quantity"].describe()

count     9288.000000
mean       -29.885228
std       1145.786965
min     -80995.000000
25%         -6.000000
50%         -2.000000
75%         -1.000000
max         -1.000000
Name: Quantity, dtype: float64

In [22]:
df[
    (df["Quantity"] < 0) &
    (~df["InvoiceNo"].astype(str).str.startswith("C"))
]["InvoiceNo"].head(20)

2406    536589
4347    536764
7188    536996
7189    536997
7190    536998
7192    537000
7193    537001
7195    537003
7196    537004
7197    537005
7198    537006
7199    537007
7200    537008
7201    537009
7202    537010
7203    537011
7204    537012
7205    537013
7206    537014
7207    537015
Name: InvoiceNo, dtype: object

In [23]:
df[df["InvoiceNo"] == "536589"]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [24]:
df[df["InvoiceNo"] == "536589"][[
    "InvoiceNo",
    "StockCode",
    "Description",
    "Quantity",
    "InvoiceDate",
    "UnitPrice",
    "CustomerID"
]]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID]
Index: []

In [25]:
(df["Quantity"] < 0).sum()

np.int64(10624)

In [26]:
(df["InvoiceNo"].astype(str).str.startswith("C")).sum()

np.int64(9288)

In [27]:
df[df["InvoiceNo"].astype(str).str.startswith("A")].shape

(3, 8)

In [28]:
df[df["InvoiceNo"].astype(str).str.startswith("A")].head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299982,A563185,B,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,NaN,United Kingdom
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [29]:
df[df["InvoiceNo"].astype(str).str.startswith("A")]["Quantity"].describe()

count    3.0
mean     1.0
std      0.0
min      1.0
25%      1.0
50%      1.0
75%      1.0
max      1.0
Name: Quantity, dtype: float64

In [30]:
df[
    (df["Quantity"] < 0) &
    (~df["InvoiceNo"].astype(str).str.startswith("C")) &
    (~df["InvoiceNo"].astype(str).str.startswith("A"))
].head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,2010-12-03 15:39:00,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,2010-12-03 15:41:00,0.0,NaN,United Kingdom

In [31]:
df[
    (df["Quantity"] < 0) &
    (~df["InvoiceNo"].astype(str).str.startswith("C")) &
    (~df["InvoiceNo"].astype(str).str.startswith("A"))
].shape

(1336, 8)

In [32]:
df[
    (df["Quantity"] < 0) &
    (~df["InvoiceNo"].astype(str).str.startswith("C")) &
    (~df["InvoiceNo"].astype(str).str.startswith("A"))
]["UnitPrice"].value_counts()

UnitPrice
0.0    1336
Name: count, dtype: int64

In [33]:
df["CustomerID"].nunique()

4372

In [34]:
df["CustomerID"].isnull().sum()

np.int64(135080)

**Data Cleaning**

In [114]:
#removed transactions where CustomerID
df_clean = df.dropna(subset=["CustomerID"])

In [36]:
df_clean["CustomerID"].nunique()

4372

In [37]:
df_clean.shape

(406829, 8)

In [115]:
#Since all the C-prefixed transactions had negative quantities, indicating cancellation/return-type transactions. We removed these aswell
df_clean = df_clean[
    ~df_clean["InvoiceNo"].astype(str).str.startswith("C")
]

In [39]:
df_clean.shape

(397924, 8)

In [40]:
df_clean["InvoiceNo"].astype(str).str.startswith("C").sum()

np.int64(0)

In [117]:
# A-Prefixed were accounting adjustments rather than customer purchases and they had no CustomerID so they were already 
# removed when we removed missing CustomerIDs

df_clean[df_clean["InvoiceNo"].astype(str).str.startswith("A")]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [42]:
df_clean[df_clean["Quantity"] < 0].shape

(0, 8)

In [118]:
#Saved the cleaned dataset in a CSV
df_clean.to_csv("../data/clean_transactions.csv", index=False)

In [44]:
df_clean.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [45]:
df_clean.shape

(397924, 8)

In [119]:
#checking the transaction dates for cleaned dataset
df_clean["InvoiceDate"].min()

Timestamp('2010-12-01 08:26:00')

In [47]:
df_clean["InvoiceDate"].max()

Timestamp('2011-12-09 12:50:00')

In [120]:
#cutoff date - Since we need 30 days of future data to determine whether someone purchased again.
#We have to move 30 days backward 

cutoff_date = df_clean["InvoiceDate"].max() - pd.Timedelta(days=30)

cutoff_date

Timestamp('2011-11-09 12:50:00')

In [51]:
#separating the clean data into the feature period and the target period.
feature_data = df_clean[df_clean["InvoiceDate"] <= cutoff_date]

In [52]:
target_data = df_clean[df_clean["InvoiceDate"] > cutoff_date]

In [53]:
feature_data.shape

(332343, 8)

In [54]:
target_data.shape

(65581, 8)

In [55]:
feature_data["InvoiceDate"].min(), feature_data["InvoiceDate"].max()

(Timestamp('2010-12-01 08:26:00'), Timestamp('2011-11-09 12:49:00'))

In [56]:
target_data["InvoiceDate"].min(), target_data["InvoiceDate"].max()

(Timestamp('2011-11-09 13:12:00'), Timestamp('2011-12-09 12:50:00'))

**Feature Engineering**

Since the dataset was transactional, but our model needs customer-level information

In [60]:
#Feature - 1: Recency calculation
last_purchase = feature_data.groupby("CustomerID")["InvoiceDate"].max()

In [58]:
recency = (cutoff_date - last_purchase).dt.days

In [59]:
recency.head()

CustomerID
12346.0    295
12347.0      9
12348.0     44
12350.0    279
12352.0      5
Name: InvoiceDate, dtype: int64

In [61]:
#Feature 2: Frequency
frequency = feature_data.groupby("CustomerID")["InvoiceNo"].nunique()

In [62]:
frequency.head()

CustomerID
12346.0    1
12347.0    6
12348.0    4
12350.0    1
12352.0    8
Name: InvoiceNo, dtype: int64

In [63]:
#Feature 3: Monetary
feature_data["TotalAmount"] = feature_data["Quantity"] * feature_data["UnitPrice"]

In [64]:
feature_data[["Quantity", "UnitPrice", "TotalAmount"]].head()

   Quantity  UnitPrice  TotalAmount
0         6       2.55        15.30
1         6       3.39        20.34
2         8       2.75        22.00
3         6       3.39        20.34
4         6       3.39        20.34

In [65]:
#Calculate Monetary per customer
monetary = feature_data.groupby("CustomerID")["TotalAmount"].sum()

In [66]:
monetary.head()

CustomerID
12346.0    77183.60
12347.0     4085.18
12348.0     1797.24
12350.0      334.40
12352.0     2506.04
Name: TotalAmount, dtype: float64

In [68]:
rfm = pd.concat([recency, frequency, monetary], axis=1)
rfm.head()

            InvoiceDate  InvoiceNo  TotalAmount
CustomerID
12346.0             295          1     77183.60
12347.0               9          6      4085.18
12348.0              44          4      1797.24
12350.0             279          1       334.40
12352.0               5          8      2506.04

In [70]:
rfm.columns = ["Recency", "Frequency", "Monetary"]
rfm.head()

            Recency  Frequency  Monetary
CustomerID
12346.0         295          1  77183.60
12347.0           9          6   4085.18
12348.0          44          4   1797.24
12350.0         279          1    334.40
12352.0           5          8   2506.04

In [72]:
#Feature 4:Total Quantity
total_quantity = feature_data.groupby("CustomerID")["Quantity"].sum()
total_quantity.head()

CustomerID
12346.0    74215
12347.0     2266
12348.0     2341
12350.0      197
12352.0      536
Name: Quantity, dtype: int64

In [75]:
#Feature 5: Unique Products
unique_products = feature_data.groupby("CustomerID")["StockCode"].nunique()
unique_products.head()

CustomerID
12346.0      1
12347.0    100
12348.0     22
12350.0     17
12352.0     59
Name: StockCode, dtype: int64

In [78]:
rfm["UniqueProducts"] = unique_products
rfm.head()

            Recency  Frequency  Monetary  UniqueProducts
CustomerID
12346.0         295          1  77183.60               1
12347.0           9          6   4085.18             100
12348.0          44          4   1797.24              22
12350.0         279          1    334.40              17
12352.0           5          8   2506.04              59

In [79]:
#Feature 6:Average Order Value
rfm["AverageOrderValue"] = rfm["Monetary"] / rfm["Frequency"]
rfm.head()

            Recency  Frequency  Monetary  UniqueProducts  AverageOrderValue
CustomerID
12346.0         295          1  77183.60               1       77183.600000
12347.0           9          6   4085.18             100         680.863333
12348.0          44          4   1797.24              22         449.310000
12350.0         279          1    334.40              17         334.400000
12352.0           5          8   2506.04              59         313.255000

In [80]:
#Feature 7: Purchase Days
feature_data["PurchaseDate"] = feature_data["InvoiceDate"].dt.date

In [82]:
unique_purchase_days = feature_data.groupby("CustomerID")["PurchaseDate"].nunique()
unique_purchase_days.head()

CustomerID
12346.0    1
12347.0    6
12348.0    4
12350.0    1
12352.0    7
Name: PurchaseDate, dtype: int64

In [84]:
rfm["UniquePurchaseDays"] = unique_purchase_days
rfm.head()

,Recency,Frequency,Monetary,UniqueProducts,AverageOrderValue,UniquePurchaseDays
CustomerID,,,,,,
12346.0,295,1,77183.60,1,77183.600000,1
12347.0,9,6,4085.18,100,680.863333,6
12348.0,44,4,1797.24,22,449.310000,4
12350.0,279,1,334.40,17,334.400000,1
12352.0,5,8,2506.04,59,313.255000,7

In [85]:
#Feature 8: Customer Lifespan
first_purchase = feature_data.groupby("CustomerID")["InvoiceDate"].min()

In [86]:
customer_lifespan = (last_purchase - first_purchase).dt.days

In [87]:
customer_lifespan.head()

CustomerID
12346.0      0
12347.0    327
12348.0    282
12350.0      0
12352.0    260
Name: InvoiceDate, dtype: int64

In [88]:
#Calculating target data
repeat_customers = target_data["CustomerID"].unique()

In [89]:
len(repeat_customers)

1649

In [112]:
#Creating the target (label) in our table
rfm["Target"] = rfm.index.isin(repeat_customers).astype(int)
rfm.head()

,Recency,Frequency,Monetary,UniqueProducts,AverageOrderValue,UniquePurchaseDays,Target,CustomerLifespan,OrdersLast30Days
CustomerID,,,,,,,,,
12346.0,295,1,77183.60,1,77183.600000,1,0,0,0
12347.0,9,6,4085.18,100,680.863333,6,1,327,1
12348.0,44,4,1797.24,22,449.310000,4,0,282,0
12350.0,279,1,334.40,17,334.400000,1,0,0,0
12352.0,5,8,2506.04,59,313.255000,7,0,260,1

In [91]:
rfm["Target"].value_counts()

Target
0    2690
1    1380
Name: count, dtype: int64

In [92]:
#Checking the complete dataset and its data types/missing values before adding more features
rfm.shape

(4070, 7)

In [94]:
rfm.isnull().sum()

Recency               0
Frequency             0
Monetary              0
UniqueProducts        0
AverageOrderValue     0
UniquePurchaseDays    0
Target                0
dtype: int64

In [95]:
rfm.dtypes

Recency                 int64
Frequency               int64
Monetary              float64
UniqueProducts          int64
AverageOrderValue     float64
UniquePurchaseDays      int64
Target                  int64
dtype: object

In [96]:
rfm["CustomerLifespan"] = customer_lifespan

In [97]:
rfm.shape

(4070, 8)

In [98]:
rfm.isnull().sum()

Recency               0
Frequency             0
Monetary              0
UniqueProducts        0
AverageOrderValue     0
UniquePurchaseDays    0
Target                0
CustomerLifespan      0
dtype: int64

In [107]:
#Feature 9 - OrdersLast30Days 
last_30_days_start = cutoff_date - pd.Timedelta(days=30)
last_30_days_start

Timestamp('2011-10-10 12:50:00')

In [102]:
orders_last_30_days = (
    feature_data[
        feature_data["InvoiceDate"] > last_30_days_start
    ]
    .groupby("CustomerID")["InvoiceNo"]
    .nunique()
)

In [103]:
orders_last_30_days.head()

CustomerID
12347.0    1
12352.0    1
12357.0    1
12359.0    1
12360.0    1
Name: InvoiceNo, dtype: int64

In [104]:
rfm["OrdersLast30Days"] = orders_last_30_days

In [105]:
rfm["OrdersLast30Days"] = rfm["OrdersLast30Days"].fillna(0).astype(int)

In [109]:
rfm.shape

(4070, 9)

In [121]:
rfm.head()
#Validating our customer-level dataset

,Recency,Frequency,Monetary,UniqueProducts,AverageOrderValue,UniquePurchaseDays,Target,CustomerLifespan,OrdersLast30Days
CustomerID,,,,,,,,,
12346.0,295,1,77183.60,1,77183.600000,1,0,0,0
12347.0,9,6,4085.18,100,680.863333,6,1,327,1
12348.0,44,4,1797.24,22,449.310000,4,0,282,0
12350.0,279,1,334.40,17,334.400000,1,0,0,0
12352.0,5,8,2506.04,59,313.255000,7,0,260,1

In [111]:
rfm.describe()

,Recency,Frequency,Monetary,UniqueProducts,AverageOrderValue,UniquePurchaseDays,Target,CustomerLifespan,OrdersLast30Days
count,4070.000000,4070.000000,4070.000000,4070.000000,4070.000000,4070.000000,4070.000000,4070.000000,4070.000000
mean,92.340786,3.881327,1857.572458,56.896314,408.295791,3.512039,0.339066,113.164128,0.510319
std,95.350702,6.782034,8024.826222,78.521281,1306.637500,5.316683,0.473451,119.452734,1.014162
min,0.000000,1.000000,2.900000,1.000000,2.900000,1.000000,0.000000,0.000000,0.000000
25%,19.000000,1.000000,298.087500,15.000000,178.430000,1.000000,0.000000,0.000000,0.000000
50%,49.000000,2.000000,640.550000,33.000000,298.837500,2.000000,0.000000,74.000000,0.000000
75%,149.000000,4.000000,1543.617500,71.000000,435.724250,4.000000,1.000000,223.000000,1.000000
max,343.000000,164.000000,247885.680000,1633.000000,77183.600000,109.000000,1.000000,343.000000,26.000000

**Data Validation**

In [122]:
rfm.describe().T

,count,mean,std,min,25%,50%,75%,max
Recency,4070.0,92.340786,95.350702,0.0,19.0000,49.0000,149.00000,343.00
Frequency,4070.0,3.881327,6.782034,1.0,1.0000,2.0000,4.00000,164.00
Monetary,4070.0,1857.572458,8024.826222,2.9,298.0875,640.5500,1543.61750,247885.68
UniqueProducts,4070.0,56.896314,78.521281,1.0,15.0000,33.0000,71.00000,1633.00
AverageOrderValue,4070.0,408.295791,1306.637500,2.9,178.4300,298.8375,435.72425,77183.60
UniquePurchaseDays,4070.0,3.512039,5.316683,1.0,1.0000,2.0000,4.00000,109.00
Target,4070.0,0.339066,0.473451,0.0,0.0000,0.0000,1.00000,1.00
CustomerLifespan,4070.0,113.164128,119.452734,0.0,0.0000,74.0000,223.00000,343.00
OrdersLast30Days,4070.0,0.510319,1.014162,0.0,0.0000,0.0000,1.00000,26.00

**Separating Features(X) and Target (Y)**

In [127]:
X = rfm.drop("Target", axis=1)

In [128]:
Y = rfm["Target"]

In [129]:
X.shape

(4070, 8)

In [130]:
Y.shape

(4070,)

**Splitting training and testing data**

In [133]:
import sklearn

In [136]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.20,
    random_state=42,
    stratify=Y
)

In [138]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((3256, 8), (814, 8), (3256,), (814,))

In [139]:
#feature scaling
from sklearn.preprocessing import StandardScaler

In [140]:
scaler = StandardScaler()

In [141]:
X_train_scaled = scaler.fit_transform(X_train)

In [142]:
X_test_scaled = scaler.transform(X_test)

In [143]:
X_train_scaled.shape, X_test_scaled.shape

((3256, 8), (814, 8))

**Model Training**

In [144]:
#We are starting of with Logistic Regression since it is binary classification problem.
from sklearn.linear_model import LogisticRegression

In [146]:
model = LogisticRegression(random_state=42)

In [147]:
model.fit(X_train_scaled, Y_train)

LogisticRegression(random_state=42)

In [148]:
Y_pred = model.predict(X_test_scaled)

In [149]:
Y_pred[:20]

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [150]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(Y_test, Y_pred)
precision = precision_score(Y_test, Y_pred)
recall = recall_score(Y_test, Y_pred)
f1 = f1_score(Y_test, Y_pred)

accuracy, precision, recall, f1

(0.7248157248157249, 0.6625, 0.38405797101449274, 0.48623853211009177)

In [151]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, Y_pred)

cm

array([[484,  54],
       [170, 106]])

In [152]:
model.coef_

array([[-0.24854339, -0.13343898, -0.01560069,  0.38391063, -0.17450945,
         1.18477976,  0.02127258,  0.08403557]])

In [153]:
coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_[0]
})

coefficients

              Feature  Coefficient
0             Recency    -0.248543
1           Frequency    -0.133439
2            Monetary    -0.015601
3      UniqueProducts     0.383911
4   AverageOrderValue    -0.174509
5  UniquePurchaseDays     1.184780
6    CustomerLifespan     0.021273
7    OrdersLast30Days     0.084036